[package]
name = "agreeter"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
greetd_ipc = "0.10.3"
rpassword = "7.4.0"
wayland-client = "0.31.8"
wayland-protocols-wlr = "0.3.6"
